
[functions.strowallet-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/strowallet-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/strowallet-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/strowallet-proxy/*.html" ]

[functions.clubkonnect-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/clubkonnect-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clubkonnect-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clubkonnect-proxy/*.html" ]

[functions.verify-account]
enabled = true
verify_jwt = true
import_map = "./functions/verify-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-account/*.html" ]

[functions.moon-phase]
enabled = true
verify_jwt = false
entrypoint = "./functions/moon-phase/index.ts"

[functions.send-push]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-push/index.ts"
